name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Build project
        run: nix build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./result/www
